<?php
namespace App\ScriptManagement;
    class ScriptProvider{
         //base in base_path()/public directory
         /***
          /assets/js
          /js/components 
         ***/
         protected static $bundles = [
            'primary-loader'=>[
                'attr'=>'async',
                'single_file'=>1,
                'output_file'=>'/dist/js/primary-loader.js?v=2',
                'files'=>[
                    '/js/components/loader.js'
                ]
            ],
            'priority-one'=>[
                'attr'=>null,
                'single_file'=>1,
                'output_file'=>'/dist/js/priority-one.min.js?v=13',
                'files'=>[
                    '/assets/js/LocaleManager.js',
                    '/assets/js/vsapi_jto.js',
                    '/assets/js/priority-load.js',
                ]
            ],
            'primary'=>[
                'attr'=>null,
                'single_file'=>1,
                'output_file'=>'/dist/js/dms.primary.js?v=2',
                'files'=>[
                    '/assets/material-js/jquery.min.js',
                    '/assets/js/Chart/Chart.js',
                ]
            ],
           'pdfmake'=>[
                'attr'=>'defer',
                'single_file'=>0,
                'minify'=>0,
                'output_file'=>'/dist/js/vs.pdfmake.js',
                'files'=>[
                    '/assets/js/pdfmake.min.js',
                    '/assets/js/vfs_fonts.js'
                ]
           ],
           'primary-defer'=>[
                'attr'=>'defer',
                'single_file'=>1,
                'output_file'=>'/dist/js/dms.primary-defer.js?v=53',
                'files'=>[
                    '/assets/js/string_san.js',
                    '/assets/js/vsutil.js',
                    '/assets/js/sweetalert2.all.min.js',
                    '/assets/js/sweetalert2.toast.js',
                    '/assets/js/ExchangeManager.js',
                    '/assets/js/expandableTableRow.js',
                    '/assets/vendors/general/popper.js/dist/umd/popper.js',
                    '/assets/material-js/bootstrap.min.js',
                    '/assets/js/validator.js',
                    '/assets/js/cv_interact.js',
                    '/assets/js/datehelper.js',
                    '/assets/js/date.js',
                    '/assets/js/jquery.datepicker2.js',
                    '/assets/js/select2.min.js',
                    '/assets/js/initializeSelect2.js',
                    '/assets/js/toastr.min.js',
                    '/assets/js/init.toastr.js',
                    '/assets/js/demo1/scripts.bundle.js',
                    '/assets/js/datatables.bundle.min.js',/** to be removed soon */
                    '/assets/js/browsercontrol.js'
                ]
                ,'no-minify'=>[
                    '/assets/js/crypto-js.js', 
                ]
                ],
               'components'=>[
                    'attr'=>'defer',
                    'single_file'=>1,
                    'output_file'=>'/dist/js/dms.components.js?v=202',
                    'files'=>[
                        '/assets/js/VSRoute.js',
                        '/js/layout/main.js?v=1',
                        '/assets/js/formUtils.js',
                        '/js/components/dms.utils.js',
                        '/js/components/DialogFilter.js',
                        //'/js/components/UnauthComponent.js',
                        '/js/components/PDFReport.js',
                        //'/js/components/ImageBox.js',
                        '/js/components/ImageHelper.js',
                        '/js/components/FileChooser.js',
                        '/assets/js/ListView.js',
                        'js/components/DashboardComponent.js',
                        '/js/components/CompanyComponent.js',
                        '/js/components/CompletedPackageListComponent.js',
                        'js/components/DeliveryPriceComponent.js',
                        'js/components/DeliveryZoneComponent.js',
                        'js/components/DriverListComponent.js?v=1',
                        'js/components/DriverPaymentComponent.js',
                        'js/components/MerchantBalancesCompoment.js',
                        'js/components/DriverBalancesCompoment.js',
                        'js/components/ExchangeRatesComponent.js',
                        'js/components/GeneralSettingsComponent.js',
                        '/assets/js/InputBoxes.js',
                        'js/components/LocationComponent.js?v=1',
                        'js/components/MobileBrandImagesComponent.js',
                        'js/components/PackageListComponent.js',
                        'js/components/FindPersonDialog.js',
                        'js/components/PickupListComponent.js',
                        'js/components/MagicEntryUtil.js',
                        'js/components/MagicEntryDialog.js',
                        'js/components/PriceSettingsComponent.js',
                        'js/components/ProductCategoriesComponent.js',
                        'js/components/RemarksComponent.js',
                        'js/components/OrderImagesComponent.js',
                        'js/components/PromotionComponent.js',
                        'js/components/ReportCenterComponent.js',
                        'js/components/SalesAgentsComponent.js',
                        'js/components/SenderListComponent.js?v=1',
                        'js/components/SenderPaymentComponent.js',
                        'js/components/TripListComponent.js',
                        'js/components/RoleManagementComponent.js',
                        'js/components/UserManagementComponent.js',
                        'assets/js/pusher/pusher.min.js',
                        '/js/components/pusher_client_houxpress.js',
                        //'/js/components/pusher_client_dms.js'
                    ]

                    ],
                    'report-scripts'=>[
                        'attr'=>'defer',
                        'single_file'=>1,
                        'output_file'=>'/dist/js/report-scripts.js',
                        'files'=>[
                            '/assets/material-js/jquery.min.js',
                            '/assets/material-js/bootstrap.min.js'
                        ]
                    ]
         ];

         static function bundle($bundle_name=null){
            if(!$bundle_name) return [];
             return isset(self::$bundles[$bundle_name])?self::$bundles[$bundle_name]:[];
         }

        static function getBundles(){
            return self::$bundles;
        }
    }
?>
