<?php

return [
    'default_minification' => true,
    'default_obfuscation' => false,
'reserved_names' => [
        '^VSRoute$',
        '^AuthManager$',
        '^GeneralDialog$',
        '^ListView$',
        '^LocaleManager$',
        '^FilterPanel$',
        '^UMExpandItemView$',
        '^ExpandableTableRowConfig$',
        '^ExpandableRowConfig$',
        '^VSDropdownMenu$',
        '^VSDropdownButton$',
        '^ItemsView$',
        '^DateTimePicker$',
        '^FileChooser$',
        '^VSUtil$',
        '^init$',
        '^setDebug$',
        '^main_view$',
        '^wasm_bindgen$',
        '^OpenFilex$',
        '^ShowConfirmDialog$',
        '^showConfirmDialog$',
        '^cv_interact$',
        '^InputBox1$',
        '^InputBox2$',
        '^ImageHelper$',
        '^ImageBox$',
        '^KTApp$','^KTUtil$','^KTLayout$',
        '^OptionEditor$',
        '^VSMoney$',
        '^vsapi$',
        '^validator$',
        '^Validator$',
        '^DateHelper$',
        '^StringSanitizer$',
        '^Sanitizer$',
        '^JsonToExcel$'
    ],
];