-- ----------------------------
-- Table structure for `zones`
-- ----------------------------
delete from `order`;
delete from `order_receivers`;
delete from `package`;
delete from `delivery`;

DROP TABLE IF EXISTS `zones`;
CREATE TABLE `zones` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `branch_id` int(10) NOT NULL,
  `zone_code` varchar(15) NOT NULL,
  `zone_name` varchar(150) NOT NULL,
  `country_id` int(10) NOT NULL,
  `city_id` int(10) NOT NULL,
  `district_id` int(10) DEFAULT NULL,
  `commune_id` int(10) DEFAULT NULL,
  `price` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT 'price = default price, generally for average item size or weight. ',
  `zone_type` varchar(30) DEFAULT NULL,
  `create_user` varchar(35) DEFAULT NULL,
  `create_date` timestamp NULL DEFAULT NULL,
  `description` varchar(150) DEFAULT NULL,
  `fast_price` decimal(10,2) DEFAULT NULL,
  `normal_price` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=350 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of zones1
-- ----------------------------
INSERT INTO `zones` VALUES ('95', '1', 'A1 VRBT', 'Bus វិរៈ​ប៊ុន​ថាំ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('96', '1', 'A2 KPT', 'Bus កា​ពី​តូល', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('97', '1', 'A3 RMN', 'Bus រិទ្ធ​មុនី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('98', '1', 'A4 SRY', 'Bus សូរិយា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('99', '1', 'A5 KR', 'Kerry Express', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('100', '1', 'A6 ASBP', 'BUS អា​ស៊ី​បូពា៍', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('101', '1', 'A7 JAT', 'J and T', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('102', '1', 'A8', 'Bus សូរិយា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('103', '1', 'A9 GTS', 'GTS ផ្សារ​ថ្មី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('104', '1', 'C10 YLPT', 'យក​លុយ​ពី​TAXI', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('105', '1', 'C11 DTSNB', 'ដាក់​តាក់​ស៊ី​ណា​ក៏​បាន', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('106', '1', 'C12 DTSMLL', 'ដាក់​តាក់​ស៊ី ​មាន​លេខ​ឡាន', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('107', '1', 'C13 TD', 'ថ្ម​ដា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('108', '1', 'C14 STDN', 'ស្តុប​ដេ​អិន', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('109', '1', 'C15 PDM', 'ផ្សា​រ​ឌុយ​មិច', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('110', '1', 'C16 PT', 'ផ្សារ​ថ្មី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('111', '1', 'C17 PSL', 'ផ្សារ​ស៊ី​ឡិប', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('112', '1', 'C18 ORS', 'អូ​ឬ​ស្សី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('113', '1', 'C19 PKPK', 'ផ្លូវ​កម្ពុជា​ក្រោម', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('114', '1', 'C20 STP', 'ស្តុប​ទេព​ផន', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('115', '1', 'C21 PDB', 'ផ្សារ​ដេប៉ូ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('116', '1', 'C22 SOLP', 'សា្តត​អូ​ឡាំ​ពេជ្រ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('117', '1', 'C23 TSP', 'ទួល​ស្វាយ​ព្រៃ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('118', '1', 'C24 BRKL', 'បុ​រី​កី​ឡា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('119', '1', 'C25 PORS', 'ផ្សារ​អូរ​ឬស្សី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('120', '1', 'C26 OLP', 'អូ​ឡាំ​ពេជ្រ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('121', '1', 'C27 VK', 'វត្ត​កោះ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('122', '1', 'C28 SLYT', 'សា​លា​យុ​គន្ធរ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('123', '1', 'C29 PNM', 'ផ្សារ​នាគ​មាស', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('124', '1', 'C30 POLP', 'ផ្សារ​អូរ​ឡាំ​ពិច', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('125', '1', 'C31 TS', 'ទួល​ស្លែង', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('126', '1', 'C32 PKRS', 'ផ្សារ​ឃ្លាំង​រំ​សេវ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('127', '1', 'C33 PDK', 'ផ្សារ​ដើម​គរ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('128', '1', 'C34 MDY', 'ម៉ុង​ឌី​យ៉ាល់', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('129', '1', 'C35 KRR', 'គិ​រី​រម្យ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('130', '1', 'C36 JSSMK', 'ជា​ស៊ីម​សាម​គ្គី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('131', '1', 'C37 PLS', 'ពេទ្យ​លោក​សង្ឃ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('132', '1', 'C38 TL123', 'ទឹក​ល្អក់​ (១២៣)', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('133', '1', 'C39 BSL', 'បឹង​សា​ឡាង', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('134', '1', 'C40 STM', 'សន្ធរ​មុខ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('135', '1', 'C41 PKD', 'ផ្សារ​កណ្តាល', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('136', '1', 'C42 SLIFL', 'សា​លា IFL', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('137', '1', 'C43 SLRUPP', 'សា​លា RUPP', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('138', '1', 'C44 SN12', 'សំ​ណង់​១២', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('139', '1', 'C45 OBK', 'អូរ​បែក​ក្អម', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('140', '1', 'C46 PKK', 'ផ្សារ​កាប់​គោ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('141', '1', 'C47 PHL', 'ផ្សារ​ហេង​លី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('142', '1', 'C48 SLST', 'ជិត​សា​លា​ស៊ី​តិច', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('143', '1', 'C49 BT', 'បាក់​ទូក', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('144', '1', 'C50 PSTM', 'ផ្សារ​ស៊ី​ធី​ម៉ល', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('145', '1', 'C51 SKD', 'ស្តុប​កោស​ដូង', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('146', '1', 'C52 JL', 'ចេន​ឡា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('147', '1', 'C54 PKMJ', 'ពេទ្យ​កុមារ​ជាតិ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('148', '1', 'C55 BSD', 'ក្រោយ​ប្រេ​ស៊ី​ដង់', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('149', '1', 'C56 SLTN', 'សា​លា​តិច​ណូ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('150', '1', 'C57 TLK', 'ត្រ​ឡោក​បែក', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('151', '1', 'C58 TPR', 'ទួល​ស្វាយ​ព្រៃ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('152', '1', 'C59 SNK', 'ស្តុប NOKIA', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('153', '1', 'C60 ChT', 'ឈូក​ទិព្វ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('154', '1', 'C61 PSMK', 'ផ្សារ​សាម​គ្គី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('155', '1', 'C62 SPC', 'ស្តុប​ពេទ្យ​ចិន', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('156', '1', 'C63 TTP', 'ទួល​ទំ​ពូង', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('157', '1', 'C64 BKK', 'បឹង​កេង​កង', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('158', '1', 'C65 BTB', 'បឹង​ត្រ​បែក', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('159', '1', 'C66 SBK', 'ស្ដុប​បូក​គោ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('160', '1', 'C67 CKM', 'ចំ​ការ​មន', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('161', '1', 'C68 AK42', 'អាគារ42 ជាន់', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('162', '1', 'C69 P271', 'ផ្លូវ​271', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('163', '1', 'C70 PPS', 'ផ្សារ​Pencil', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('164', '1', 'C71 VD', 'វ៉ាន់​ដា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('165', '1', 'C72 SBK', 'ស្តុប​បូក​គោ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('166', '1', 'C73 SLBB', 'សា​លា​បៀល​ប្រាយ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('167', '1', 'C74 SLKH', 'សា​លា​ក្រហម', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('168', '1', 'C75 VBT', 'វត្ត​បទុម', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('169', '1', 'C76 SNJ', 'ស្តុប​ណាន​ជីន', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('170', '1', 'C77 UP', 'សា​លា​ពេទ្យ​UP', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('171', '1', 'C78 SRY', 'ផ្សារ​សូ​រិ​យា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('172', '1', 'C79 SBS', 'ស្តុប​បា​សាក់', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('173', '1', 'C80 KNDY', 'កា​ណា​ឌី​យ៉ា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('174', '1', 'C81 PSHN', 'ផ្លូវ​សី​ហនុ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('175', '1', 'C82 PNRD', 'ផ្លូវ​ន​រោ​ត្តម', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('176', '1', 'C83 TC', 'ទូត​ចិន', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('177', '1', 'C84 CTM', 'ច​តុ​មុខ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('178', '1', 'C85 SLSSV', 'សា​លា​ស៊ី​សុ​វ័ត្តិ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('179', '1', 'C86 KR', 'ក្រោយ​វាំង', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('180', '1', 'C87 AO1', 'Aeon 1', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('181', '1', 'C88 KP', 'កោះ​ពេជ្រ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('182', '1', 'C89 SLRULE', 'សា​លា​ Rule', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('183', '1', 'C90 NGW', 'Naga world', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('184', '1', 'C91 TVN', 'ទូត​វៀត​ណាម', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('185', '1', 'C92 VMR', 'វិ​មាន​ឯក​រាជ្យ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('186', '1', 'C93 PSVN', 'ផ្សារ​សុវណ្ណា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('187', '1', 'C94 AKVN', 'អគារ​វឌ្ឍ​នៈ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('188', '1', 'C95 BT7', 'Beltie7', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('189', '1', 'C96 P360', 'ផ្លូវ​ 360', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('190', '1', 'C97 FD', 'Fast Delivery', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('191', '1', 'C98 SLVD', 'សា​លា​វ៉ាន់​ដា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('192', '1', 'C99 PMST', 'ផ្លូវ​ម៉ៅ​សេ​ទុង', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('193', '1', 'C100 PRS', 'ពេទ្យ​រុ​ស្សី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('194', '1', 'C101 Taxi', 'ដាក់​តាក់​ស៊ី​ណា​ក៏​បាន', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('195', '1', 'C102 Taxi', 'ដាក់​តាក់​ស៊ី ​មាន​លេខ​ឡាន', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('196', '1', 'C103 Taxi', 'យក​លុយ​ពី​TAXI​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('197', '1', 'D110 PSJ', 'ពោធ៍​សែន​ជ័យ​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('198', '1', 'D111 BPL', 'បឹង​ព្រ​លឹត', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('199', '1', 'D112 PDH', 'ផ្សារ​ដី​ហុយ​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('200', '1', 'D113 PSJR', 'ផ្សារ​សេន​ជូ​រី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('201', '1', 'D114 PCT', 'ពោធ៍​ចិន​តុង​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('202', '1', 'D115 SS', 'សែន​សុខ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('203', '1', 'D116 TSK', 'ទួល​សង្កែ​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('204', '1', 'D117 CK', 'Camko', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('205', '1', 'D118 BRCK', 'បុ​រី​កាំ​កូ​ស៊ី​ធី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('206', '1', 'D119 RMCCV)', 'រង្វង់​មូល​ជ្រោយ​ចង្វារ​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('207', '1', 'D120 PSMC', 'ផ្សារ​ស្ទឹង​មាន​ជ័យ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('208', '1', 'D121 SL', 'សូ​ឡា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('209', '1', 'D122 VSKS', 'វត្ត​សន្សំ​កុ​សល​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('210', '1', 'D123 P2004', 'ផ្លូវ​2004', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('211', '1', 'D124 P2002', 'ផ្លូវ​2002', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('212', '1', 'D125 PPS', 'ផ្សារ​ផេ​សេ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('213', '1', 'D126 PDTK', 'ផ្សារ​ដើម​ថ្កូវ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('214', '1', 'D127 BTP', 'បឹង​ទំ​ពុន', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('215', '1', 'D128 KTH', 'ក្បាល​ថ្នល់​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('216', '1', 'D129 TK', 'ទួល​គោក', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('217', '1', 'D130 BCH', 'បឹង​ឈូក', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('218', '1', 'D131 VP', 'វត្ត​ភ្នំ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('219', '1', 'D132 SLVS', 'សា​លា​វេ​ស្ទើន​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('220', '1', 'D133 CM', 'Camed', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('221', '1', 'D134 TTh', 'ទឹក​ថ្លា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('222', '1', 'D135 RVMJN', 'រង្វង់​មូល​ជូត​ណាត​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('223', '1', 'D135 PT', 'ផ្សារ​តូច', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('224', '1', 'D137 VNV', 'វត្ត​នាគ​វ័ន្ត', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('225', '1', 'D138 KM', 'កាល់​ម៉ែត្រ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('226', '1', 'D139 TK', 'ទួល​គោក', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('227', '1', 'D140 PMRT', 'ផ្លូវ​ម៉ុង​រទ្ធី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('228', '1', 'D141 MD', 'មៃដា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('229', '1', 'D142 SLIU', 'សា​លា IU', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('230', '1', 'D143 VT', 'វត្ត​ទូល', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('231', '1', 'D144 SLPK', 'សា​លា​ពញា​ក្រែក', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('232', '1', 'D145 KD', 'ខណ្ឌ​ដង្កោ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('233', '1', 'D146 PPC', 'ផ្សារ​ PC', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('234', '1', 'D147 PJYR', 'ផ្សារ​ជេន​យូ​រី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('235', '1', 'D148 PSK', 'ភូមិ​សាម​គ្គី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('236', '1', 'D149 PTPCH', 'ផ្សារ​ត្រ​ពាំង​ឈូក', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('237', '1', 'D150 SJ', 'ស្តាត​ចាស់​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('238', '1', 'D151 PJ', 'ផ្សារ​ចាស់​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('239', '1', 'D152 SLANV', 'សា​លា​អ​នុ​វត្ត​ជិត​ផ្លូវ​២០០២', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('240', '1', 'D153 ETV', 'ឥ​ន្រ្ត​ទេ​វី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('241', '1', 'D154 VATM', 'វត្ត​អង់​តា​មិញ​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('242', '1', 'D155 VDBP', 'វត្តដំបូកខ្ពស់', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('243', '1', 'D156 PMA', 'ផ្សារ​មាន់​អាំង​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('244', '1', 'D157 JAL', 'ចាក់​អង្រែ​លើ​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('245', '1', 'D158 JOR', 'ចាក់​អង្រែ​ក្រោម​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('246', '1', 'D159', 'Pa​ra​gon', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('247', '1', 'D160 BK', 'បឹង​កក់​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('248', '1', 'E165 CM', 'ផ្សារ​ឈូក​មាស​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('249', '1', 'E166 CV2', 'ឈូក​វ៉ា​២', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('250', '1', 'E167 SROD', 'វត្ត​សំ​រោង​អណ្តែត', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('251', '1', 'E168 BBT', 'ផ្សារ​បឹង​បៃ​តង', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('252', '1', 'E169 PT', 'ផ្សារ​ព្រែក​ទា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('253', '1', 'E170', 'CTN', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('254', '1', 'E173 RSK', 'សា​លា​ខណ្ឌ​ឬស្សី​កែវ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('255', '1', 'E174 KS', 'វត្ត​កៀន​ឃ្លាំង', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('256', '1', 'E175 PL', 'ព្រែក​លាប', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('257', '1', 'E176 RR', 'បុ​រី​រុង​រឿង', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('258', '1', 'E177 BL', 'ស្ពាន​បា​លេ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('259', '1', 'E178 CSPP', 'ផ្លូវ​ជា​សូ​ផា​រ៉ា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('260', '1', 'E179 ANGKOR', 'បុ​រី​អង្គរ​ភ្នំ​ពេញ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('261', '1', 'E180 PPT', 'ភ្នំ​ពេញ​ថ្មី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('262', '1', 'E181 SLNT', 'សា​លា​ន័រ​តុន', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('263', '1', 'E182 CC', 'ចោម​ចៅ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('264', '1', 'E183 JKD', 'ចំ​ការ​ដូង', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('265', '1', 'E184 JPV', 'ជម្ពូ​វន្ត័​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('266', '1', 'E185 SBM', 'វត្ត​សំ​បូរ​មាស', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('267', '1', 'E186 AR1', 'ផ្សារ​ឯក​រាជ្រ​១', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('268', '1', 'E187 JKD', 'ពិ​ភព​ថ្មី​ចំ​ការ​ដូង', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('269', '1', 'E188 TPT', 'ផ្សារ​ទំ​ពាំង​ថ្លឹង​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('270', '1', 'E189 VS', 'ផ្លូវ​វេង​ស្រេង​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('271', '1', 'E190 TPR', 'ទួល​ពង្រ​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('272', '1', 'E191 PHN', 'ផ្លូវ​ហា​ណួយ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('273', '1', 'D161 COR', 'ចាក់​អង្រែ​ក្រោម', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('274', '1', 'E192 CB', 'ច្បារ​អំ​ពៅ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('275', '1', 'E193 PP', 'ព្រែក​ប្រា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('276', '1', 'E194 BS', 'បឹង​ស្នោរ​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('277', '1', 'E195 TKM', 'តា​ខ្មៅ​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('278', '1', 'E196', 'Aeon 2', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('279', '1', 'E197 SKHOTEL', 'សុ​ខា​ Hotel', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('280', '1', 'E198 PL', 'មុខ​ប្រ​លាន​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('281', '1', 'E199 CM', 'ផ្សារ​ឈូក​មាស', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('282', '1', 'E200WPN', 'វត្ត​ពោធិ​ញាន​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('283', '1', 'E201RSK', 'ឬ​ស្សី​កែវ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('284', '1', 'C104RP', 'royal palace', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('285', '1', 'E203KL7', 'ផ្សារ​គីឡូ​លេខ​ 7', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('286', '1', 'E204KL6', 'ផ្សារ​គី​ឡូ​លេខ​ 6', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('287', '1', 'E205271', 'ផ្លូវ​371', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('288', '1', 'F225CVM', 'ឈូក​រ៉ា​១', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('289', '1', 'F226KPP', 'គ្រេន​ភ្នំ​ពេញ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('290', '1', 'F227OD', 'អូ​ដឹម', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('291', '1', 'F228PS', 'ព្រៃ​សរ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('292', '1', 'F229STP2', 'បុ​រី​សន្តិ​ភាព​២', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('293', '1', 'F230KB', 'កំ​បូល​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('294', '1', 'F231VS', 'បុ​រី​វាល​ស្បូវ​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('295', '1', 'F232PP', 'ព្រែក​ភ្នៅ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('296', '1', 'F233WVS', 'វត្ត​វាល​ស្បូវ​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('297', '1', 'F234SBKPJ', 'ស្រា​បៀរ​ក​ម្ពុ​ជា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('298', '1', 'F235TNKS', 'ទំ​នប់​កប់​ស្រូវ​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('299', '1', 'F236WS', 'វត្ត​ស្លែង', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('300', '1', 'F237PA', 'ព្រែក​អែង', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('301', '1', 'F238VMJJ', 'វិ​មាន​ឈ្នះ​ៗ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('302', '1', 'F239RVKS', 'វង្វង់​កួរ​ស្រូវ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('303', '1', 'F240PH', 'ព្រែក​ហូ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('304', '1', 'F241PHSM', 'ផ្លូវ​៦០​ម៉ែត្រ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('305', '1', 'F242SLYP', 'ស្ពាន​លី​យ៉ុង​ផាត់​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('306', '1', 'F243HRVTKM', 'ហួស​រង្វ​ង់មូល​តា​ខ្មៅ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('307', '1', 'C105TS', 'ផ្លូវ​ត្រ​សក់​ផ្អែម​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('308', '1', 'E206PL', 'ព្រែក​លាប​(បុ​រី​មេ​គង្គ​ Royal)', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('309', '1', 'E207KT', 'ក្រំាង​ធ្នង់', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('310', '1', 'E208WKK', 'វត្ត​គៀន​ឃ្លាំង​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('311', '1', 'C106SDP', 'ផ្លូវ​សម្ដេច​ប៉ាន​', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('312', '1', 'D162SL', 'សរ​ឡា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('313', '1', 'D163lB', 'លូ​ប្រាំ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('314', '1', 'D164S7MKR', 'ស្ពាន់​៧​មករា', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('315', '1', 'F244RVMKS', 'រង្វង់​មូល​គួរ​ស្រូវ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('316', '1', 'F245BJ', 'បែក​ចាន', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('317', '1', 'C107MNR', 'ផ្លូវ​មុន្នី​រ៉េត', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('318', '1', 'E209KNCT', 'កា​ណា​ស៊ី​ធី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('319', '1', 'C108K2', 'ក្តាន់​២', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('320', '1', 'F246PJL3', 'ផ្លូវ​ជាតិ​លេខ​៣', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('321', '1', 'F247WJPK', 'វត្តចំពុះក្អែក', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('322', '1', 'C109MNV', 'ផ្លូវមុន្នីវង្ស', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('323', '1', 'E210TKS', 'តាំងក្រសាំង', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('324', '1', 'E211BSLT', 'បឹងសាឡាងថ្មី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('325', '1', 'E212BRR', 'បុរីរីទ្ធ ទួលសង្កែ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('326', '1', 'E213PDK', 'ភូមិដើមខ្វិត', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('327', '1', 'E214PDOP', 'ផ្សារដើមអំពិល', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('328', '1', 'E215WPS', 'វត្តព្រែកឬស្សី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('329', '1', 'E216PTKM', 'ផ្សារតាខ្មៅ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('330', '1', 'E217SPSR', 'ស្ពានព្រែកសំរោង', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('331', '1', 'E218BTSD', 'បន្ទាយសម្តេច', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('332', '1', 'E219KPSN', 'កំពុងសំណាញ់', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('333', '1', 'E220WTM', 'វត្តតាខ្មៅ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('334', '1', 'E221PRS', 'ភូមិឬស្សី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('335', '1', 'E222SN', 'សូនី', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('336', '1', 'E223PJ', 'ព្រៃជ្រៃ', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
INSERT INTO `zones` VALUES ('337', '1', 'E224JA', 'ជើងឯក', '14', '13', null, null, '0.00', 'Local', null, null, null, null, null);
